# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    environment: cloud-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/algamoney-api:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #Login no Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '340.0.0'
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      #Confere a variável de ambiente    
      - name: GCP_CREDENTIALS
        run: echo "json_content:$(cat C:\Keys\algamoney-api-391316-27ecb29e2e82.json)" >> $GITHUB_ENV
        
      #Autenticação
      - name: Authenticate with Google Cloud
        run: |
          echo $json_content
      
      - name: Deploy to Google Cloud
        run: gcloud app deploy
        
